/* =============================================
   github-stats.js — Loads data/stats.json (generated by
   scripts/fetch-github-stats.sh) and updates:
     - [data-oss-stat="externalProjects"] / [data-oss-stat="mergedPRs"]
     - [data-stat-key="..."] counters in the stats section
     - #featured-prs-list-en / -ar  (latest merged external PRs)
     - #featured-prs-updated-en / -ar (timestamp)
     - hm-en / hm-ar heatmaps via window.CV.heatmapData (consumed by animations.js)
   Falls back silently to the static values if stats.json is missing
   (e.g. when running offline or before the first fetcher run).
   ============================================= */

(function() {
  'use strict';

  var STATS_URL = 'data/stats.json';
  // Resolve relative path — works when index.html is at site root.
  // For nested pages we'd compute prefix, but this file is only loaded
  // by index.html so plain relative is fine.

  function toArabicNumerals(s) {
    var map = {'0':'٠','1':'١','2':'٢','3':'٣','4':'٤','5':'٥','6':'٦','7':'٧','8':'٨','9':'٩',',':'٬'};
    return String(s).replace(/[0-9,]/g, function(c) { return map[c] || c; });
  }

  function fmt(n, isAr) {
    var s = Number(n).toLocaleString('en-US');
    return isAr ? toArabicNumerals(s) : s;
  }

  function applyStats(stats) {
    if (!stats || !stats.summary) return;
    var summary = stats.summary;

    // OSS section badges (data-oss-stat attribute)
    document.querySelectorAll('[data-oss-stat]').forEach(function(el) {
      var key = el.getAttribute('data-oss-stat');
      var val = summary[key];
      if (typeof val !== 'number') return;
      // Round down to a clean threshold so the badge doesn't churn day-to-day:
      // 113 → 100+, 571 → 500+, 24 → 20+
      var rounded;
      if (val >= 100) rounded = Math.floor(val / 100) * 100;
      else if (val >= 20) rounded = Math.floor(val / 10) * 10;
      else rounded = val;
      var isAr = el.hasAttribute('data-ar');
      var prefix = isAr ? '+' : '';
      var suffix = isAr ? '' : '+';
      el.textContent = prefix + fmt(rounded, isAr) + suffix;
    });

    // Stats section counters — feed the animate-to-target machinery if present.
    // We update data-count and let the existing counter animation re-run.
    document.querySelectorAll('[data-stat-key]').forEach(function(el) {
      var key = el.getAttribute('data-stat-key');
      var val = summary[key];
      if (typeof val !== 'number') return;
      var rounded;
      if (val >= 100) rounded = Math.floor(val / 100) * 100;
      else if (val >= 20) rounded = Math.floor(val / 10) * 10;
      else rounded = val;
      el.setAttribute('data-count', String(rounded));
      // If already animated (has counter-done), update text immediately
      if (el.classList.contains('counter-done')) {
        el.textContent = String(rounded);
      }
    });

    // Latest PRs strip
    renderFeaturedPRs(stats);

    // Stash heatmap for animations.js to consume
    if (Array.isArray(stats.heatmap) && stats.heatmap.length) {
      window.CV = window.CV || {};
      window.CV.heatmapData = stats.heatmap;
      // If animations.js already ran initHeatmap before stats.json loaded,
      // re-run to overwrite synthetic squares with real ones.
      if (typeof window.initHeatmap === 'function') {
        window.initHeatmap();
      }
    }
  }

  function renderFeaturedPRs(stats) {
    var prs = stats.latestPRs || [];
    if (!prs.length) return;
    var updated = stats.lastUpdated ? new Date(stats.lastUpdated) : null;

    [['featured-prs-en', 'en'], ['featured-prs-ar', 'ar']].forEach(function(pair) {
      var wrap = document.getElementById(pair[0]);
      if (!wrap) return;
      var lang = pair[1];
      var listEl = document.getElementById('featured-prs-list-' + lang);
      var stampEl = document.getElementById('featured-prs-updated-' + lang);
      if (!listEl) return;
      var isAr = lang === 'ar';

      listEl.innerHTML = '';
      prs.slice(0, 5).forEach(function(pr) {
        var a = document.createElement('a');
        a.className = 'featured-pr';
        a.href = pr.url;
        a.target = '_blank';
        a.rel = 'noopener noreferrer';
        var when = pr.mergedAt ? new Date(pr.mergedAt) : null;
        var whenTxt = when
          ? when.toLocaleDateString(isAr ? 'ar-EG' : 'en-US', { month: 'short', day: 'numeric', year: 'numeric' })
          : '';
        a.innerHTML =
          '<div class="featured-pr-repo">' + escapeHtml(pr.repo || '') + '</div>' +
          '<div class="featured-pr-title">' + escapeHtml(pr.title || '') + '</div>' +
          '<div class="featured-pr-date">' + escapeHtml(whenTxt) + '</div>';
        listEl.appendChild(a);
      });
      if (stampEl && updated) {
        var u = updated.toLocaleDateString(isAr ? 'ar-EG' : 'en-US', { month: 'short', day: 'numeric' });
        stampEl.textContent = isAr ? '· محدّث ' + u : '· updated ' + u;
      }
      wrap.hidden = false;
    });
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, function(c) {
      return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];
    });
  }

  function load() {
    fetch(STATS_URL, { cache: 'default' })
      .then(function(r) { return r.ok ? r.json() : null; })
      .then(function(stats) { if (stats) applyStats(stats); })
      .catch(function() { /* silent — keep static fallback values */ });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', load);
  } else {
    load();
  }
})();
