#!/usr/bin/env bash
# Regenerates css/bundle.css and css/utilities.css by concatenating
# the canonical source files. The site is loaded via the bundles, but
# sub-pages also link the individual source files — keep both in sync.
#
# Run after editing any of: main.css, themes.css, components.css,
# animations.css, arabic.css, responsive.css.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CSS="$ROOT/css"

build() {
  local target="$1"; shift
  local files=("$@")
  echo "→ building $target"
  {
    echo "/* ============================================="
    echo "   $(basename "$target") — auto-generated by scripts/build-css.sh"
    echo "   ============================================= */"
    echo ""
    for src in "${files[@]}"; do
      echo "/* === $(basename "$src") === */"
      cat "$CSS/$src"
      echo ""
    done
  } > "$CSS/$target"
  echo "   $(wc -l < "$CSS/$target") lines"
}

build bundle.css    main.css themes.css components.css
build utilities.css animations.css arabic.css responsive.css

echo "✓ CSS bundles regenerated"
